export const IPC_CHANNELS = {
  // Main communication
  SEND_COMMAND: 'SEND_COMMAND',
  BACKEND_RESPONSE: 'BACKEND_RESPONSE',

  // Progress events
  PROGRESS_UPDATE: 'PROGRESS_UPDATE',
  ERROR_UPDATE: 'ERROR_UPDATE',
  WARNING_UPDATE: 'WARNING_UPDATE',

  // Window management
  WINDOW_MINIMIZE: 'WINDOW_MINIMIZE',
  WINDOW_MAXIMIZE: 'WINDOW_MAXIMIZE',
  WINDOW_CLOSE: 'WINDOW_CLOSE',
  WINDOW_STATE_CHANGED: 'WINDOW_STATE_CHANGED',

  // Menu actions
  MENU_ACTION: 'MENU_ACTION',

  // App info
  GET_APP_VERSION: 'GET_APP_VERSION',
  GET_PLATFORM: 'GET_PLATFORM',

  // File operations
  SELECT_DIRECTORY: 'SELECT_DIRECTORY',
  SELECT_FILE: 'SELECT_FILE',
  OPEN_EXTERNAL: 'OPEN_EXTERNAL',

  // Development
  OPEN_DEV_TOOLS: 'OPEN_DEV_TOOLS',
  RELOAD_APP: 'RELOAD_APP'
} as const;

export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];

